site_name: NanoCut Control
site_description: Documentation for the NanoCut Control application
site_author: Johannes Nilsson
repo_url: https://github.com/nwjnilsson/nanocut-control
nav:
  - Home: index.md
  - Installation: installation.md
  - Getting Started: getting-started.md
  - CAM View: cam-view.md
  - Control View: control-view.md
  - Machine Parameters: machine-parameters.md
  - Keyboard Shortcuts: keyboard-shortcuts.md
theme: material
